Add cidr_to_range function to generate a range of IP addresses
Yelp/puppet-netstdlib pull request #11
Opened 2017-05-04 00:18 UTC by rayward

This excludes the network and broadcast addresses.

```puppet
ips = cidr_to_range('192.168.1.0/29')

# returns this array
[
  '192.168.1.1',
  '192.168.1.2',
  '192.168.1.3',
  '192.168.1.4',
  '192.168.1.5',
  '192.168.1.6',
]
```

2017-05-05 16:31 UTC, somic requested changes
Thank you! Just several ruby things.

2017-05-05 16:31 UTC, somic commented on spec/functions/cidr_to_range_spec.rb
> +describe 'cidr_to_range' do
Could you also please add a test case for /32 cidr to ensure it returns empty list.

2017-05-07 23:25 UTC, rayward commented
@somic I've implemented the changes as requested!

2017-05-08 15:56 UTC, somic requested changes

2017-05-08 15:56 UTC, somic commented on lib/puppet/parser/functions/cidr_to_range.rb
> +    unless arg.respond_to?('to_s')
Looks good! Please take this entire "unless" out (pretty much everything in ruby will have :to_s method) and we are good to go.

2017-05-08 23:17 UTC, rayward commented on lib/puppet/parser/functions/cidr_to_range.rb
> +    unless arg.respond_to?('to_s')
Thanks, yeh that was a bit useless. I've replaced it with a stricter `String` check as any other data type coming into this function would be invalid.

2017-05-10 15:16 UTC, merged

2017-05-10 15:16 UTC, somic commented
Thank you!